# Generated by Django 2.2 on 2019-04-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(default='none', max_length=6),
        ),
    ]
