# Generated by Django 2.2 on 2019-04-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190411_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordgame',
            name='correctGuesses',
            field=models.CharField(default='NULL', max_length=120),
            preserve_default=False,
        ),
    ]
